alpha: 0.8
bbox_thr: 0.3
det_cat_id: 0
det_checkpoint: "../ckpt/rtmdet_m_8xb32-100e_coco-obj365-person-235e8209.pth"
det_config: "../config/rtmdet_m_640-8xb32_coco-person.py"
device: cuda:0
draw_bbox: false
draw_heatmap: false
input_root: ''
kpt_thr: 0.3
nms_thr: 0.3
output_root: ''
pose_checkpoint: "../ckpt/rtmw-x_simcc-cocktail14_pt-ucoco_270e-384x288-f840f204_20231122.pth"
pose_config: "../config/rtmw-x_8xb320-270e_cocktail14-384x288.py"
radius: 3
show: false
show_kpt_idx: false
skeleton_style: mmpose
thickness: 1
output_fps: 25
visualize: false
